In [1]:
import numpy as np

In [4]:
v_hor_np=np.array([1,2])
print(v_hor_np)

[1 2]


In [5]:
v1=np.zeros((5,))
print(v1)

[0. 0. 0. 0. 0.]


In [6]:
v2=np.ones((5,))
print(v2)

[1. 1. 1. 1. 1.]


In [7]:
v_vert=np.array([[1], [2]])

In [9]:
print(v_vert)

[[1]
 [2]]


In [10]:
v_vert_z=np.zeros((5,1))
print(v_vert_z)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [11]:
v_vert_o=np.ones((5,1))
print(v_vert_o)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [12]:
m_sqr_arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
m=np.matrix('1 2 3; 4 5 6; 7 8 9')
diag=np.diag(m)
print(diag)

[1 5 9]


In [14]:
md=np.diag(np.diag(m))
print(md)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [15]:
m_eye=np.eye(5)
print(m_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
m_z=np.zeros((3,3))
print(m_z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
a=np.matrix('1 2 3; 4 5 6')
print(a)

[[1 2 3]
 [4 5 6]]


In [18]:
a_t=a.transpose()
print(a_t)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
R = (a.T).T
print(R)

[[1 2 3]
 [4 5 6]]


In [21]:
a=np.matrix('1 2; 3 4')
b=np.matrix('5 6; 7 8')
l=(a.dot(b)).T
r=(b.T).dot(a.T)
print(l)
print(r)

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


In [22]:
a=np.matrix('1 2 3; 4 5 6')
k=3
l=(k*a).T
r=k*(a.T)
print(l)
print(r)

[[ 3 12]
 [ 6 15]
 [ 9 18]]
[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [23]:
a=np.matrix('1 6 3; 8 2 7')
b=np.matrix('8 1 5; 6 9 12')
c=a+b
print(c)

[[ 9  7  8]
 [14 11 19]]


In [24]:
a=np.matrix('1 2 3; 4 5 6')
b=np.matrix('7 8; 9 1; 2 3')
c=a.dot(b)
print(c)

[[31 19]
 [85 55]]


In [25]:
a=np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(a)
np.linalg.det(a)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


-14.000000000000009

In [26]:
a=np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(a)
np.linalg.det(a)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


0.0

In [27]:
a=np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(a)
k=2
b=a.copy()
b[2,:]=k*b[2,:]
print(b)
det_a=round(np.linalg.det(a), 3)
det_b=round(np.linalg.det(b), 3)
det_a*k
det_b

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]


-28.0

In [28]:
a=np.matrix('1 -3; 2 5')
a_inv=np.linalg.inv(a)
a_inv_inv=np.linalg.inv(a_inv)
print(a)
print(a_inv_inv)

[[ 1 -3]
 [ 2  5]]
[[ 1. -3.]
 [ 2.  5.]]


In [29]:
print(m_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
rank=np.linalg.matrix_rank(m_eye)
print(rank)

5
